### ISSUE TITLE
VSCode: AWS resource throws exception when accessing properties

### ISSUE THREAD

**Issue by jkotalik** [radius-project/radius#6384]
### Steps to reproduce (required)

1. Following bicep file:
```bicep
import aws as aws

import radius as radius

param environment string
param location string = 'global'

resource s3 'AWS.S3/Bucket@default' = {
  name: 'my-bucket-14829032'
  properties: {
    BucketName: 'my-bucket-14829032'
    AccessControl: 'PublicRead'
  }
}

// get a radius container which uses the s3 bucket
resource app 'Applications.Core/applications@2022-03-15-privatepreview' = {
  name: 'webapp'
  location: location
  properties: {
    environment: environment
  }
}

resource frontend 'Applications.Core/containers@2022-03-15-privatepreview' = {
  name: 'frontend'
  location: location
  properties: {
    application: app.id
    container: {
      env: {
        BUCKET_NAME: s3.properties. <- after executing s3.properties., this exception is thrown from bicep
      }
      image: 'jkotalik.azurecr.io/awstutorialapp:latest'
    }
  }
}

``` 

```
[Error - 1:54:32 PM] Request textDocument/completion failed.
  Message: Internal Error - System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   at Bicep.Core.TypeSystem.Aws.AwsResourceTypeFactory.ToTypeSymbol(TypeBase typeBase, Boolean isResourceBodyType) in /home/runner/work/bicep/bicep/src/Bicep.Core/TypeSystem/Aws/AwsResourceTypeFactory.cs:line 87
   at Bicep.Core.TypeSystem.Aws.AwsResourceTypeFactory.<>c__DisplayClass3_0.<GetTypeSymbol>b__0(TypeBase serializedType) in /home/runner/work/bicep/bicep/src/Bicep.Core/TypeSystem/Aws/AwsResourceTypeFactory.cs:line 29
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Bicep.Core.TypeSystem.Aws.AwsResourceTypeFactory.GetTypeSymbol(TypeBase serializedType, Boolean isResourceBodyType) in /home/runner/work/bicep/bicep/src/Bicep.Core/TypeSystem/Aws/AwsResourceTypeFactory.cs:line 29
   at Bicep.Core.TypeSystem.Aws.AwsResourceTypeFactory.<>c__DisplayClass4_0.<GetTypeReference>b__0() in /home/runner/work/bicep/bicep/src/Bicep.Core/TypeSystem/Aws/AwsResourceTypeFactory.cs:line 32
   at Bicep.Core.TypeSystem.DeferredTypeReference.get_Type() in /home/runner/work/bicep/bicep/src/Bicep.Core/TypeSystem/DeferredTypeReference.cs:line 16
   at Bicep.LanguageServer.Completions.BicepCompletionProvider.FormatPropertyDocumentation(TypeProperty property) in /home/runner/work/bicep/bicep/src/Bicep.LangServer/Completions/BicepCompletionProvider.cs:line 1576
   at Bicep.LanguageServer.Completions.BicepCompletionProvider.CreatePropertyAccessCompletion(TypeProperty property, BicepFile tree, PropertyAccessSyntax propertyAccess, Range replacementRange, CompletionPriority priority) in /home/runner/work/bicep/bicep/src/Bicep.LangServer/Completions/BicepCompletionProvider.cs:line 1280
   at Bicep.LanguageServer.Completions.BicepCompletionProvider.<>c__DisplayClass35_0.<GetMemberAccessCompletions>b__1(TypeProperty p) in /home/runner/work/bicep/bicep/src/Bicep.LangServer/Completions/BicepCompletionProvider.cs:line 859
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.ConcatIterator`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
   at System.Linq.Enumerable.ConcatNIterator`1.LazyToArray()
   at OmniSharp.Extensions.LanguageServer.Protocol.Models.CompletionList..ctor(IEnumerable`1 items, Boolean isIncomplete)
   at Bicep.LanguageServer.Handlers.BicepCompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /home/runner/work/bicep/bicep/src/Bicep.LangServer/Handlers/BicepCompletionHandler.cs:line 56
   at OmniSharp.Extensions.JsonRpc.JsonRpcServerServiceCollectionExtensions.RequestHandlerDecorator`2.Handle(T request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 

```

VSCode version: `ms-azuretools.rad-vscode-bicep-0.10.145-gc06d8e02c9/bicepLanguageServer/Bicep.LangServer.dll'.`

[AB#4457](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/4457)

**Comment by nicolejms** [comment]
very old so closing
