### ISSUE TITLE
Deployment fails using parameters file input from KeyVault

### ISSUE THREAD

**Issue by v-esteves** [radius-project/radius#6396]
## Bug information
When deploying the eshop app.bicep, using a parameters file for the adminPassword input, I'm getting the following error:

Error: ResourceDeploymentClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InternalServerError" Message="Internal server error."

The parameter value is a reference to a secret on a key vault.

```
{
    "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
    "contentVersion": "1.0.0.0",
    "parameters": {
      "adminPassword": {
        "reference": {
          "keyVault": {
            "id": "/subscriptions/A_VALID_SUBSCRIPTION/resourceGroups/RGCM2LILABVE001/providers/Microsoft.KeyVault/vaults/A_KV"
          },
          "secretName": "ExamplePassword"
        }
      }
    }
  }
```

### Steps to reproduce (required)
1 - Clone the repo.
2 - Go to the eshop app
3 - Create local ARM JSON parameter file
4 - Execute `rad deploy app.bicep --parameters @paramenters.json`

### Observed behavior (required)
Operation is aborted with the previous error message.

Logs:

`
[40m[32minfo[39m[22m[49m: DeploymentEngine.Engine.RadiusDeploymentEngine[0]
      Starting deployment rad-deploy-e43dd42e-682a-42e5-a9a3-229413bef96c
[41m[30mfail[39m[22m[49m: Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.NotImplementedException: The method or operation is not implemented.
         at DeploymentEngine.Engine.TempDeploymentEngine`1.ResolveDeploymentParameterReferences(Dictionary`2 parameters) in /src/src/DeploymentEngine/Engine/TempDeploymentEngine.cs:line 468
         at DeploymentEngine.Engine.TempDeploymentEngine`1.<>c__DisplayClass16_0.<<PrepareParametersForDeployment>b__0>d.MoveNext() in /src/src/DeploymentEngine/Engine/TempDeploymentEngine.cs:line 660
      --- End of stack trace from previous location ---
         at DeploymentEngine.Engine.TemplateExceptionUtils.<>c__DisplayClass4_0`1.<<HandleTemplateException>b__0>d.MoveNext() in /src/src/DeploymentEngine/Engine/ExceptionHandler.cs:line 70
      --- End of stack trace from previous location ---
         at DeploymentEngine.Engine.TemplateExceptionUtils.HandleTemplateExceptionInternal[T](Func`1 protectedMethod, String deploymentId) in /src/src/DeploymentEngine/Engine/ExceptionHandler.cs:line 233
         at DeploymentEngine.Engine.TempDeploymentEngine`1.ProcessDeployment(DeploymentContextWithScopeDefinition deploymentContext, DeploymentContent definition, String originalDeploymentName, Boolean isNestedDeployment, Boolean validateOnly, Uri serviceEndpointUri, CancellationToken cancellationToken, InsensitiveDictionary`1 functionEvaluationOverwrites) in /src/src/DeploymentEngine/Engine/TempDeploymentEngine.cs:line 453
         at DeploymentEngine.Engine.RadiusDeploymentEngine`1.ProcessDeployment(DeploymentContextWithScopeDefinition deploymentContext, DeploymentContent definition, String originalDeploymentName, Boolean isNestedDeployment, Boolean validateOnly, Uri serviceEndpointUri, CancellationToken cancellationToken, InsensitiveDictionary`1 functionEvaluationOverwrites) in /src/src/DeploymentEngine/Engine/RadiusDeploymentEngine.cs:line 73
         at DeploymentEngine.Controllers.DeploymentUCPController.ProcessDeploymentRequest(DeploymentRequestContext context, DeploymentUCPContent deploymentUCPContent, DeploymentContent deploymentContent, String originalDeploymentName, Boolean isNestedDeployment, Boolean validateOnly, InsensitiveConcurrentDictionary`1 overwrites, CancellationToken cancellationToken) in /src/src/DeploymentEngine/Controllers/DeploymentUCPController.cs:line 203
         at DeploymentEngine.Controllers.DeploymentUCPController.ProcessResourceGroupDeploymentRequest(String resourceGroupName, String deploymentName, String originalDeploymentName, DeploymentUCPContent deploymentUCPContent, DeploymentContent deploymentContent, InsensitiveConcurrentDictionary`1 deploymentResourceGroups, CancellationToken cancellationToken) in /src/src/DeploymentEngine/Controllers/DeploymentUCPController.cs:line 172
         at DeploymentEngine.Controllers.DeploymentUCPController.PutDeployment(Object content, String resourceGroupName, String deploymentName, CancellationToken cancellationToken) in /src/src/DeploymentEngine/Controllers/DeploymentUCPController.cs:line 100
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at DeploymentEngine.Extensibility.ExtensibilityExceptionHandlingMiddleware.InvokeAsync(HttpContext context) in /src/src/DeploymentEngine/Extensibility/ExtensibilityExceptionHandlingMiddleware.cs:line 31
         at DeploymentEngine.ArmErrorMiddleware.Invoke(HttpContext httpContext) in /src/src/DeploymentEngine/ArmErrorMiddleware.cs:line 31
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
`

### Desired behavior (required)
Deploy the application using the referenced value from the parameters file, so I can avoid having hardcoded secrets on files on a repo.

### Workaround (optional)
Deploy using the value as input on the CLI command

### rad Version (required)
RELEASE   VERSION   BICEP      COMMIT
0.14.0       v0.14.0        0.10.144  f5a45c96ab1b2799b9781c4572fc6c05a174d3d3

### Operating system (required)
macOS Ventura - i9 chip

## Additional context

[AB#5052](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/5052)

[AB#9688](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9688)

**Comment by nicolejms** [comment]
very old so closing
