### ISSUE TITLE
Test failure due to log after test completes in UCP integration tests

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6454]
## Context

It's against the rules to use `testing.T.Log` after the test associated with the `testing.T` instance has completed. We found a case of this in our automated test runs.

This is a non-deterministic failure and doesn't reproduce all of the time. Since the root cause is "logging after the test has finished" it is definitely timing related.

A quickf ix for this would be to disable the logging since it's only needed to diagnose problems.

A better solution would be to build a wrapper for the test logger that shuts down when the test completes. It's not possible in all circumstances to prevent this kind of problem. We've hit this in a few places in the code when using dependencies we don't control.

## Details

From: https://github.com/radius-project/radius/actions/runs/6482555392/job/17602307102?pr=6445

```
 panic: Log in goroutine after Test_RadiusPlane_ResourceAsync has completed: "ts"="2023-10-11 12:50:12.232183" "level"=0 "msg"="Message loop stopped..."


goroutine 467 [running]:
testing.(*common).logDepth(0xc002348340, {0xc002922c30, 0x4c}, 0x3)
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1022 +0x674
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1004
testing.(*common).Log(0xc002348340, {0xc0027b3cf0, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.21.1/x64/src/testing/testing.go:1045 +0x7e
github.com/go-logr/logr/testr.logInfo({0x389cc68, 0xc002348340}, 0xc0023e2cc8, 0x0?, {0x33aa8e2, 0x17}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/testr/testr.go:101 +0x197
github.com/go-logr/logr/testr.testloggerInterface.Info({{0x0, {0x3888868, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x1, 0xc0000db270}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/testr/testr.go:148 +0x106
github.com/go-logr/logr.Logger.Info({{0x38b88c8?, 0xc0022d3b00?}, 0xc00020aaf0?}, {0x33aa8e2, 0x17}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:278 +0xe4
github.com/radius-project/radius/pkg/armrpc/asyncoperation/worker.(*AsyncRequestProcessWorker).Start(0xc0022d3b60, {0x38b4730?, 0xc00020aaf0})
	/home/runner/work/radius/radius/pkg/armrpc/asyncoperation/worker/worker.go:214 +0x49f
github.com/radius-project/radius/pkg/ucp/integrationtests/testrp.AsyncResource.func3()
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testrp/async.go:86 +0x5d
created by github.com/radius-project/radius/pkg/ucp/integrationtests/testrp.AsyncResource in goroutine 376
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testrp/async.go:85 +0xfd0
FAIL	github.com/radius-project/radius/pkg/ucp/integrationtests/radius	3.567s
```

[AB#9698](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9698)

**Comment by ytimocin** [comment]
Happened again: https://github.com/radius-project/radius/actions/runs/10221277475/job/28283443714?pr=7781. I have been running into this a few times for the last few days.

**Comment by rynowak** [comment]
Fixed here: https://github.com/radius-project/radius/pull/8190
