### ISSUE TITLE
Connection values created by Radius controller are double-encoded.

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#6540]
### Steps to reproduce (required)

Run the Radius Kubernetes tutorial that's in PR here: https://github.com/radius-project/docs/pull/864

### Observed behavior (required)

When you port-forward to the app, it will crash on the TODO page. The message in the logs looks like:

```
webapp-65859486d7-x6mzj webapp node:internal/errors:496
webapp-65859486d7-x6mzj webapp     ErrorCaptureStackTrace(err);
webapp-65859486d7-x6mzj webapp     ^
webapp-65859486d7-x6mzj webapp
webapp-65859486d7-x6mzj webapp TypeError [ERR_INVALID_URL]: Invalid URL
webapp-65859486d7-x6mzj webapp     at new NodeError (node:internal/errors:405:5)
webapp-65859486d7-x6mzj webapp     at new URL (node:internal/url:637:13)
webapp-65859486d7-x6mzj webapp     at RedisClient.parseURL (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:115:76)
webapp-65859486d7-x6mzj webapp     at Commander._RedisClient_initiateOptions (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:311:36)
webapp-65859486d7-x6mzj webapp     at new RedisClient (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:77:148)
webapp-65859486d7-x6mzj webapp     at new Commander (/usr/src/app/node_modules/@redis/client/dist/lib/commander.js:44:13)
webapp-65859486d7-x6mzj webapp     at create (/usr/src/app/node_modules/@redis/client/dist/lib/client/index.js:111:16)
webapp-65859486d7-x6mzj webapp     at createClient (/usr/src/app/node_modules/redis/dist/index.js:38:38)
webapp-65859486d7-x6mzj webapp     at RedisFactory.<anonymous> (/usr/src/app/dist/db/redis.js:21:51)
webapp-65859486d7-x6mzj webapp     at Generator.next (<anonymous>) {
webapp-65859486d7-x6mzj webapp   input: 'cmVkaXM6Ly9yZWRpcy13d2d0a2M2MzY0azVjLmRlbW8uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OS8wPw',
webapp-65859486d7-x6mzj webapp   code: 'ERR_INVALID_URL'
webapp-65859486d7-x6mzj webapp }
webapp-65859486d7-x6mzj webapp
webapp-65859486d7-x6mzj webapp Node.js v18.18.2
```

### Desired behavior (required)

Tutorial works.

### Workaround (optional)

It's a tutorial. It works or it doesn't 😆 

[AB#9886](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/9886)

**Comment by rynowak** [comment]
The root cause of this is double-encoding.

The value stored in the secret created by the Radius controller is `Y21Wa2FYTTZMeTl5WldScGN5MTNkMmQwYTJNMk16WTBhelZqTG1SbGJXOHVjM1pqTG1Oc2RYTjBaWEl1Ykc5allXdzZOak0zT1M4d1B3` 

.... which base64-decodes to `cmVkaXM6Ly9yZWRpcy13d2d0a2M2MzY0azVjLmRlbW8uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OS8wPw`

.... which base64-decodes to `redis://redis-wwgtkc6364k5c.demo.svc.cluster.local:6379/0?` (the correct value).

Somewhere along the way we're storing the value incorrectly in the secret.

**Comment by rynowak** [comment]
The explanation of this behavior is here: https://github.com/weibeld/kubernetes-client-go-examples#ex5-secrets

Using the Kubernetes client from Go, you read and write secrets in their **decoded** form.
