### ISSUE TITLE
UCP Integration Test Flakiness

### ISSUE THREAD

**Issue by kachawla** [radius-project/radius#6663]
## Bug information

Test Name: Test_ResourceGroup_PUT_Update

Make test on PR workflow failed due to this test failure. Detailed logs are below -

Link to the run: https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662

```
=== Failed
=== FAIL: pkg/ucp/integrationtests/resourcegroups  (0.00s)
panic: test timed out after 10m0s
running tests:
	Test_ResourceGroup_PUT_Update (0s)

goroutine 246 [running]:
testing.(*M).startAlarm.func1()
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:2259 +0x1fc
created by time.goFunc
	/opt/hostedtoolcache/go/1.21.3/x64/src/time/sleep.go:176 +0x45

goroutine 1 [chan receive]:
testing.(*T).Run(0xc00077d380, {0x3380819, 0x1d}, 0x349c8b8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1649 +0x856
testing.runTests.func1(0x0?)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:2054 +0x85
testing.tRunner(0xc00077d380, 0xc000697af8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 +0x239
testing.runTests(0xc000365680?, {0x4aa3800, 0x6, 0x6}, {0x1c?, 0x4aded9?, 0x4ac5600?})
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:2052 +0x897
testing.(*M).Run(0xc000365680)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1925 +0xb58
main.main()
	_testmain.go:91 +0x2e5

goroutine 30 [IO wait, 9 minutes]:
internal/poll.runtime_pollWait(0x7fa1e8584eb0, 0x72)
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/netpoll.go:[343](https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662#step:7:344) +0x85
internal/poll.(*pollDesc).wait(0xc0007d0a20, 0x448a01?, 0x0)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_poll_runtime.go:84 +0xb1
internal/poll.(*pollDesc).waitRead(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0007d0a00)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_unix.go:611 +0x405
net.(*netFD).accept(0xc0007d0a00)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/fd_unix.go:172 +0x3e
net.(*TCPListener).accept(0xc0007e7680)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock_posix.go:152 +0x3e
net.(*TCPListener).Accept(0xc0007e7680)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock.go:315 +0x65
net/http.(*Server).Serve(0xc00011ac30, {0x3866850, 0xc0007e7680})
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/http/server.go:3056 +0x57f
net/http/httptest.(*Server).goServe.func1()
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/http/httptest/server.go:310 +0xab
created by net/http/httptest.(*Server).goServe in goroutine 140
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/http/httptest/server.go:308 +0xa6

goroutine 248 [runnable]:
regexp/syntax.(*parser).checkLimits(0xc000812780, 0xc0003c24d0?)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:161 +0x95
regexp/syntax.(*parser).push(0xc000812780, 0xc0003c24d0)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:327 +0xa2b
regexp/syntax.(*parser).concat(0xc000812780)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:496 +0x385
regexp/syntax.(*parser).parseRightParen(0xc000812780)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:1410 +0x39
regexp/syntax.parse({0x34067e8, 0x85}, 0xd4)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:953 +0x905
regexp/syntax.Parse(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/syntax/parse.go:891
regexp.compile({0x34067e8, 0x85}, 0x0?, 0x0)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/regexp.go:174 +0x65
regexp.Compile(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/regexp.go:137
regexp.MustCompile({0x34067e8, 0x85})
	/opt/hostedtoolcache/go/1.21.3/x64/src/regexp/regexp.go:317 +0x49
github.com/radius-project/radius/pkg/validator.parseSpecFilePath({0xc0009943c0, 0x4e})
	/home/runner/work/radius/radius/pkg/validator/loader.go:186 +0x45
github.com/radius-project/radius/pkg/validator.LoadSpec.func1({0xc0009943c0, 0x4e}, {0x3878068, 0x38987f8}, {0x0?, 0x4af9a9?})
	/home/runner/work/radius/radius/pkg/validator/loader.go:108 +0xdd
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc0009943c0, 0x4e}, {0x3878068, 0x38987f8}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:73 +0x95
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc0009942d0, 0x41}, {0x3878068, 0x38987c8}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc00071e750, 0x2e}, {0x3878068, 0x3898798}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc00071e690, 0x26}, {0x3878068, 0x3898768}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc00071e630, 0x22}, {0x3878068, 0x3898738}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc0008080a8, 0x11}, {0x3878068, 0x3898618}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0xc000958b33, 0xd}, {0x3878068, 0x38985b8}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.walkDir({0x38508c0, 0x38985a0}, {0x3847418, 0x1}, {0x38779d0, 0xc00070ab20}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:95 +0x3ae
io/fs.WalkDir({0x38508c0, 0x38985a0}, {0x3847418, 0x1}, 0xc0007438c8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/io/fs/walk.go:122 +0x116
github.com/radius-project/radius/pkg/validator.LoadSpec({0x3877ab0, 0xc0003c2070}, {0x334c992, 0x3}, {0x38508c0?, 0x38985a0}, {0xc00070ab10, 0x1, 0x1}, {0x0, ...})
	/home/runner/work/radius/radius/pkg/validator/loader.go:97 +0x318
github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD(0xc000aa0ea0, 0x[349](https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662#step:7:350)ca00)
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:277 +0x1199
github.com/radius-project/radius/pkg/ucp/integrationtests/resourcegroups.Test_ResourceGroup_PUT_Update(0x0?)
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/resourcegroups/resourcegroups_test.go:59 +0x45
testing.tRunner(0xc000aa0ea0, 0x349c8b8)
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1595 +0x239
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.21.3/x64/src/testing/testing.go:1648 +0x82b

goroutine 141 [chan receive (nil chan), 9 minutes]:
github.com/radius-project/radius/pkg/ucp/data.(*EmbeddedETCDService).Run(0xc0007ec600, {0x3877928, 0x4af7780})
	/home/runner/work/radius/radius/pkg/ucp/data/etcd.go:151 +0x1505
github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD.func1()
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:239 +0x46
created by github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD in goroutine 140
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:228 +0x3b8

goroutine 142 [select]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc0008286e0, {0x3877a40, 0xc00064e140})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:83 +0x1bd
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 141
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x24a

goroutine 143 [select, 9 minutes]:
google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run(0xc000828740, {0x3877a40, 0xc00064e190})
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:83 +0x1bd
created by google.golang.org/grpc/internal/grpcsync.NewCallbackSerializer in goroutine 141
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/internal/grpcsync/callback_serializer.go:55 +0x24a

goroutine 215 [select]:
google.golang.org/grpc.(*addrConn).resetTransport(0xc000005500)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/clientconn.go:1[368](https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662#step:7:369) +0x3ef
google.golang.org/grpc.(*addrConn).connect(0xc000005500)
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/clientconn.go:993 +0x23b
created by google.golang.org/grpc.(*acBalancerWrapper).Connect in goroutine 142
	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.57.0/balancer_conn_wrappers.go:398 +0xa7

goroutine 249 [runnable]:
internal/poll.runtime_pollClose(0x7fa1e8584cc0)
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/netpoll.go:286 +0x5d
internal/poll.(*pollDesc).close(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_poll_runtime.go:52
internal/poll.(*FD).destroy(0xc000d1c700)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_unix.go:79 +0x65
internal/poll.(*FD).decref(0xc000d1c700)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_mutex.go:213 +0x37
internal/poll.(*FD).Close(0xc000d1c700)
	/opt/hostedtoolcache/go/1.21.3/x64/src/internal/poll/fd_unix.go:104 +0x7e
net.(*netFD).Close(0xc000d1c700)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/fd_posix.go:37 +0x3e
net.(*TCPListener).close(...)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock_posix.go:160
net.(*TCPListener).Close(0xc000b7aa00)
	/opt/hostedtoolcache/go/1.21.3/x64/src/net/tcpsock.go:328 +0x6b
github.com/radius-project/radius/pkg/ucp/data.(*EmbeddedETCDService).assignPorts(0x[387](https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662#step:7:388)7928?, {0x4af7780?, 0xc00051e5a0?})
	/home/runner/work/radius/radius/pkg/ucp/data/etcd.go:243 +0x27e
github.com/radius-project/radius/pkg/ucp/data.(*EmbeddedETCDService).Run(0xc00080c300, {0x3877928, 0x4af7780})
	/home/runner/work/radius/radius/pkg/ucp/data/etcd.go:78 +0x149
github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD.func1()
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:239 +0x46
created by github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD in goroutine 248
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:228 +0x3b8
FAIL	github.com/radius-project/radius/pkg/ucp/integrationtests/resourcegroups	600.[408](https://github.com/radius-project/radius/actions/runs/6804092807/job/18500850397?pr=6662#step:7:409)s

=== FAIL: pkg/ucp/integrationtests/resourcegroups Test_ResourceGroup_PUT_Create (600.09s)
```

### Steps to reproduce (required)

Needs further investigation.

### Desired behavior (required)

The test should always pass.

**Comment by nicolejms** [comment]
potentially due to resource consumption during TF tests

**Comment by kachawla** [comment]
> potentially due to resource consumption during TF tests

As far as I have seen, UCP integration tests have been flaky even before TF tests were added, so I think we should see if running them as part of `make test` is the right thing to do.

**Comment by lakshmimsft** [comment]
Closing this issue. Reopen as needed.
