### ISSUE TITLE
`Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference` error in the controller pod

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#6841]
## Bug information
I have observed this error message in the functional test runs of some PRs in the controller pod.

`
{"severity":"info","timestamp":"2023-11-22T16:40:35.409Z","name":"controller.controller","caller":"controller/controller.go:114","message":"Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference","serviceName":"controller","version":"edge","hostName":"controller-84f587c5d6-kqhcf","controller":"deployment","controllerGroup":"apps","controllerKind":"Deployment","Deployment":{"name":"dapr-sts-manual-redis","namespace":"default-daprrp-rs-statestore-manual"},"namespace":"default-daprrp-rs-statestore-manual","name":"dapr-sts-manual-redis","reconcileID":"276efd5d-463d-41b1-8b3c-30c5312ed1fd"}
`

panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x17b5417]

goroutine 133 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:115 +0x1e5
panic({0x1974860?, 0x2cda2d0?})
	/opt/hostedtoolcache/go/1.21.4/x64/src/runtime/panic.go:914 +0x21f
github.com/radius-project/radius/pkg/controller/reconciler.(*DeploymentReconciler).Reconcile(0xc0000cb100, {0x1ed8998, 0xc000908660}, {{{0xc00095dcb0?, 0x0?}, {0xc000691068?, 0x410745?}}})
	/home/runner/work/radius/radius/pkg/controller/reconciler/deployment_reconciler.go:110 +0x3b7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1ed8998?, {0x1ed8998?, 0xc000908660?}, {{{0xc00095dcb0?, 0x18a9e60?}, {0xc000691068?, 0x1ec7010?}}})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:118 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0001ad040, {0x1ed89d0, 0xc0006ec870}, {0x1a1fb00?, 0xc0005b78c0?})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:314 +0x365
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc0001ad040, {0x1ed89d0, 0xc0006ec870})
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:265 +0x1c9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:226 +0x79
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2 in goroutine 101
	/home/runner/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.15.0/pkg/internal/controller/controller.go:222 +0x565

### Steps to reproduce (required)
1. Create a PR or run functional tests locally (the latter needs confirmation)
2. Check controller pod logs
3. See the panic

### Observed behavior (required)
Error in the controller pod.

### Desired behavior (required)
No panic

### rad Version (required)
PR

### Operating system (required)
PR

## Additional context
[msgrp_container_logs.zip](https://github.com/radius-project/radius/files/13443632/msgrp_container_logs.zip)
[daprrp_container_logs.zip](https://github.com/radius-project/radius/files/13443633/daprrp_container_logs.zip)

[AB#10470](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/10470)

**Comment by ytimocin** [comment]
```
Name:             controller-84f587c5d6-kqhcf
Namespace:        radius-system
Priority:         0
Service Account:  controller
Node:             radius-control-plane/172.18.0.2
Start Time:       Wed, 22 Nov 2023 16:39:57 +0000
Labels:           app.kubernetes.io/name=controller
                  app.kubernetes.io/part-of=radius
                  control-plane=controller
                  pod-template-hash=84f587c5d6
Annotations:      prometheus.io/path: /metrics
                  prometheus.io/port: 9090
                  prometheus.io/scrape: true
Status:           Running
IP:               10.244.0.16
IPs:
  IP:           10.244.0.16
Controlled By:  ReplicaSet/controller-84f587c5d6
Containers:
  controller:
    Container ID:  containerd://5ec2d47b0f44f52fa11a9f34eb32c653b238b5576491862ad2745ce9276a61ad
    Image:         ghcr.io/radius-project/dev/controller:pr-b3baf7160c
    Image ID:      ghcr.io/radius-project/dev/controller@sha256:d3316aebcbc7f1dc18d3f634511e166c7ee7c209fa0200407f64fcc3ff230f55
    Ports:         9443/TCP, 9090/TCP
    Host Ports:    0/TCP, 0/TCP
    Args:
      --config-file
      /etc/config/controller-config.yaml
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Wed, 22 Nov 2023 16:41:44 +0000
      Finished:     Wed, 22 Nov 2023 16:41:57 +0000
    Ready:          False
    Restart Count:  3
    Limits:
      memory:  300Mi
    Requests:
      memory:  60Mi
    Environment:
      TLS_CERT_DIR:  /var/tls/cert
      PORT:          9443
    Mounts:
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-dcfdw (ro)
      /var/tls/cert from cert (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      controller-config
    Optional:  false
  cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  controller-cert
    Optional:    false
  kube-api-access-dcfdw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                  From               Message
  ----     ------       ----                 ----               -------
  Normal   Scheduled    2m39s                default-scheduler  Successfully assigned radius-system/controller-84f587c5d6-kqhcf to radius-control-plane
  Warning  FailedMount  2m38s                kubelet            MountVolume.SetUp failed for volume "cert" : failed to sync secret cache: timed out waiting for the condition
  Normal   Pulled       2m34s                kubelet            Successfully pulled image "ghcr.io/radius-project/dev/controller:pr-b3baf7160c" in 933.190868ms (2.290805669s including waiting)
  Normal   Pulled       119s                 kubelet            Successfully pulled image "ghcr.io/radius-project/dev/controller:pr-b3baf7160c" in 136.213657ms (884.795298ms including waiting)
  Normal   Pulled       97s                  kubelet            Successfully pulled image "ghcr.io/radius-project/dev/controller:pr-b3baf7160c" in 160.095171ms (160.127321ms including waiting)
  Normal   Pulling      52s (x4 over 2m37s)  kubelet            Pulling image "ghcr.io/radius-project/dev/controller:pr-b3baf7160c"
  Normal   Created      52s (x4 over 2m34s)  kubelet            Created container controller
  Normal   Started      52s (x4 over 2m34s)  kubelet            Started container controller
  Normal   Pulled       52s                  kubelet            Successfully pulled image "ghcr.io/radius-project/dev/controller:pr-b3baf7160c" in 195.263528ms (195.277203ms including waiting)
  Warning  BackOff      9s (x6 over 110s)    kubelet            Back-off restarting failed container controller in pod controller-84f587c5d6-kqhcf_radius-system(3653a8dd-8c92-4a31-9eac-0e4d4a36ada8)
```
