### ISSUE TITLE
Unit-test `Test_AzurePlane_ProxyRequest` is flaky

### ISSUE THREAD

**Issue by youngbupark** [radius-project/radius#7407]
### Steps to reproduce

I found the same failures from the unit-test twice. 

```
=== Failed
=== FAIL: pkg/ucp/integrationtests/azure  (0.00s)
PASS
{"level":"info","ts":"2024-03-28T19:37:32.699561Z","caller":"embed/etcd.go:376","msg":"closing etcd server","name":"default","data-dir":"/tmp/ucp-etcd-data-1329603632","advertise-peer-urls":["http://localhost:42973"],"advertise-client-urls":["http://localhost:36467"]}
{"level":"warn","ts":"2024-03-28T19:37:32.699707Z","caller":"embed/serve.go:160","msg":"stopping insecure grpc server due to error","error":"accept tcp 127.0.0.1:36467: use of closed network connection"}
coverage: [no statements]
{"level":"warn","ts":"2024-03-28T19:37:32.700027Z","caller":"embed/serve.go:162","msg":"stopped insecure grpc server due to error","error":"accept tcp 127.0.0.1:36467: use of closed network connection"}
{"level":"info","ts":"2024-03-28T19:37:32.7001Z","caller":"etcdserver/server.go:1465","msg":"skipped leadership transfer for single voting member cluster","local-member-id":"55ff9246c028ed1d","current-leader-member-id":"55ff9246c028ed1d"}
panic: Log in goroutine after Test_AzurePlane_ProxyRequest has completed: "ts"="2024-03-28 19:37:32.699194" "level"=0 "msg"="Message loop stopped..."


goroutine 194 [running]:
testing.(*common).logDepth(0xc000502d00, {0xc00153c1e0, 0x4c}, 0x3)
	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1022 +0x6d4
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1004
testing.(*common).Log(0xc000502d00, {0xc001[347](https://github.com/radius-project/radius/actions/runs/8472656624/job/23215241280?pr=7405#step:7:348)870, 0x1, 0x1})
	/opt/hostedtoolcache/go/1.21.7/x64/src/testing/testing.go:1045 +0x7e
github.com/go-logr/logr/testr.logInfo({0x3983b38, 0xc000502d00}, 0xc000843cc8, 0x0?, {0x34753ea, 0x17}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/testr/testr.go:101 +0x197
github.com/go-logr/logr/testr.testloggerInterface.Info({{0x0, {0x3970128, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, 0x1, 0xc000792000}, ...}, ...)
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/testr/testr.go:148 +0x11f
github.com/go-logr/logr.Logger.Info({{0x399fe78?, 0xc00051e480?}, 0x399c2b0?}, {0x34753ea, 0x17}, {0x0, 0x0, 0x0})
	/home/runner/go/pkg/mod/github.com/go-logr/logr@v1.2.4/logr.go:278 +0xe4
github.com/radius-project/radius/pkg/armrpc/asyncoperation/worker.(*AsyncRequestProcessWorker).Start(0xc000183c80, {0x399bf30?, 0xc0003760e0})
	/home/runner/work/radius/radius/pkg/armrpc/asyncoperation/worker/worker.go:213 +0x49f
github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD.func2()
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:290 +0x5d
created by github.com/radius-project/radius/pkg/ucp/integrationtests/testserver.StartWithETCD in goroutine 141
	/home/runner/work/radius/radius/pkg/ucp/integrationtests/testserver/testserver.go:289 +0x11ab
FAIL	github.com/radius-project/radius/pkg/ucp/integrationtests/azure	1.202s

DONE 3135 tests, 7 skipped, 1 failure in 410.688s
make: *** [build/test.mk:47: test] Error 1
```

### Desired behavior

No failures

### rad Version

edge

### Would you like to support us?

- [X] Yes, I would like to support you

**Comment by nicolejms** [comment]
old unit test failure - closing
