### ISSUE TITLE
Flaky test: Test_summaryModel/Result:_Confirm

### ISSUE THREAD

**Issue by rynowak** [radius-project/radius#8044]
### Steps to reproduce

See logs: https://github.com/radius-project/radius/actions/runs/11768735276/job/32778890465?pr=8038

### Observed behavior

```txt
=== FAIL: pkg/cli/cmd/radinit Test_summaryModel/Result:_Confirm (0.05s)
    --- FAIL: Test_summaryModel/Result:_Confirm (0.05s)
panic: interface conversion: tea.Model is nil, not *radinit.summaryModel [recovered]
	panic: interface conversion: tea.Model is nil, not *radinit.summaryModel

goroutine 75 [running]:
testing.tRunner.func1.2({0x463d200, 0xc0004645a0})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1635 +0x6b6
panic({0x463d200?, 0xc0004645a0?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/radius-project/radius/pkg/cli/cmd/radinit.Test_summaryModel.func3(0xc00063b040, {0x49ddd06, 0x9}, 0xd)
	/home/runner/work/radius/radius/pkg/cli/cmd/radinit/display_test.go:73 +0x518
github.com/radius-project/radius/pkg/cli/cmd/radinit.Test_summaryModel.func4(0xc00063b040)
	/home/runner/work/radius/radius/pkg/cli/cmd/radinit/display_test.go:78 +0x49
testing.tRunner(0xc00063b040, 0xc000651c30)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 74
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1743 +0x826

=== FAIL: pkg/cli/cmd/radinit Test_summaryModel (0.05s)
```

### Desired behavior

Test passes reliably.

### rad Version

This shouldn't be a required field. 

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13669](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13669)

**Comment by ytimocin** [comment]
On-call will start working on this. On-call **can** hand it off to the next on-call but then if the issue is still not resolved it should go into the sprint planning.
