### ISSUE TITLE
Flaky test: `Test_E2E/confirm_value`

### ISSUE THREAD

**Issue by ytimocin** [radius-project/radius#8057]
### Steps to reproduce

See logs: https://github.com/radius-project/radius/actions/runs/11827197453/job/32954839983?pr=7963

### Observed behavior

```
=== Failed
=== FAIL: pkg/cli/prompt/text Test_E2E/confirm_value (0.00s)
    --- FAIL: Test_E2E/confirm_value (0.00s)
panic: interface conversion: tea.Model is nil, not text.Model [recovered]
	panic: interface conversion: tea.Model is nil, not text.Model

goroutine 51 [running]:
testing.tRunner.func1.2({0x7c0d60, 0xc000132540})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1635 +0x6b6
panic({0x7c0d60?, 0xc000132540?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/radius-project/radius/pkg/cli/prompt/text.Test_E2E.func7(0xc0001de1a0)
	/home/runner/work/radius/radius/pkg/cli/prompt/text/text_test.go:142 +0x47d
testing.tRunner(0xc0001de1a0, 0xc0001a0130)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 22
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1743 +0x826

=== FAIL: pkg/cli/prompt/text Test_E2E (0.06s)
```

### Desired behavior

Test passes reliably.

### rad Version

edge

### Additional context

Related issue: #8044.

### Would you like to support us?

- [ ] Yes, I would like to support you

[AB#13695](https://dev.azure.com/azure-octo/e61041b4-555f-47ae-95b2-4f8ab480ea57/_workitems/edit/13695)

**Comment by lakshmimsft** [comment]
is this the same/related to #7670?

**Comment by brooke-hamilton** [comment]
This test failed again: https://github.com/radius-project/radius/actions/runs/12199816888/job/34034533811. 

```text
=== Failed
=== FAIL: pkg/cli/prompt/text Test_E2E/cancel (0.00s)
    --- FAIL: Test_E2E/cancel (0.00s)
panic: interface conversion: tea.Model is nil, not text.Model [recovered]
	panic: interface conversion: tea.Model is nil, not text.Model

goroutine 15 [running]:
testing.tRunner.func1.2({0x7c0d60, 0xc00009a300})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1632 +0x3fc
testing.tRunner.func1()
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1635 +0x6b6
panic({0x7c0d60?, 0xc00009a300?})
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/runtime/panic.go:785 +0x132
github.com/radius-project/radius/pkg/cli/prompt/text.Test_E2E.func8(0xc0000d6000)
	/home/runner/work/radius/radius/pkg/cli/prompt/text/text_test.go:152 +0x46c
testing.tRunner(0xc0000d6000, 0xc000034460)
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1690 +0x227
created by testing.(*T).Run in goroutine 22
	/home/runner/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.linux-amd64/src/testing/testing.go:1743 +0x826

=== FAIL: pkg/cli/prompt/text Test_E2E (0.06s)
```

**Comment by ytimocin** [comment]
Fixed by https://github.com/radius-project/radius/pull/8053.
